### ISSUE TITLE
ODI Teams

### ISSUE THREAD

**Issue by langphil** [theodi/frontend-www#342]
As we've now grown to the point where new teams are forming, it'd be great to have this reflected on the team page for the ODI. Teams that are missing include;

Content & Learning
Business Support
Business Operations
Human Resources
International
Associates

I've been asked about being able to choose where people are placed in the hierarchy of teams on the team page - at the moment this a structured so they appear alphabetically. 

I've also been asked if we could have the associates placed at the bottom of the page. 

@Floppy @sumikasan @pezholio

**Comment by Floppy** [comment]
Deprecated by #363
