### ISSUE TITLE
ODI badge not being served over valid HTTPS

### ISSUE THREAD

**Issue by konklone** [theodi/frontend-www#360]
I'm not totally sure this is the right repo, but the ODI's badge is served at `static.theodi.org`, which has an expired HTTPS certificate:

https://static.theodi.org/assets/badge.css

This is giving all-HTTPS nodes like https://usodi.org a mixed content warning in modern browsers, with no obvious recourse besides freezing the code into their own repo (and thus having to manually sync any updates to that file the ODI makes).

**Comment by Floppy** [comment]
I think this is fixed, the certificate appears to be correct now.

**Comment by konklone** [comment]
:+1:
