### ISSUE TITLE
Code for Lead Generation Tracking Trial

### ISSUE THREAD

**Issue by carlrodriguesodi** [theodi/frontend-www#361]
Message from Patrik: Hi Guys,

We have recently signed up for a month long trial of a lead generation service to help the membership and training team identify leads. In order for the software to work, we need help adding a piece of code to the pages we would like to track (homepage, membership pages, training pages, about page). The software tells us which companies have been to the site. 

The code is as follows:

<script>

var _pt = ["E6AF1363-3E19-409A-983C-91FFE62C2CBB"];
(function(d,t){
var a=d.createElement(t),s=d.getElementsByTagName(t)[0];a.src=location.protocol+'//a1webstrategy.com/track.js';s.parentNode.insertBefore(a,s);
}(document,'script'));

</script>

Would very much appreciate the help in implementing the code. Let me know if you need further information from me.

All the best,

Patrik Wagner
Business Development
Open Data Institute
65 Clifton Street, EC2A 4JE
0757 210 5212

**Comment by Floppy** [comment]
continued via email
