### ISSUE TITLE
ODI Team 

### ISSUE THREAD

**Issue by langphil** [theodi/frontend-www#363]
Hello, 

I'd like the team page to reflect the structure of the team as it stands now. 

Currently there is no way to add individuals to the international team and culture team. 

I will put together a detailed document outlining what is needed for when this is something the tech team has time to address. 

Thank you,

Phil

@Floppy @pezholio

**Comment by Floppy** [comment]
Should we not be reflecting program structure, or the new functional team structure in some way instead? Perhaps this will be clearer after the offsite? I'm guessing new tags will be needed...

**Comment by langphil** [comment]
This is a fair point. How this is structured is entirely up for discussion. 

Do let me know where we could potentially fit this into an upcoming sprint. It would be worth having a more general face to face catch up in the near future on this and other website related items.
