### ISSUE TITLE
CSS on team page

### ISSUE THREAD

**Issue by JoePackman** [theodi/frontend-www#389]
Hello, 

There are some issues on the team page when a team member (such as Patrice) has a long name. It's pushing the their title over their department.

![team open data institute](https://cloud.githubusercontent.com/assets/7666588/8672867/136ccd18-2a2a-11e5-9a6f-585c0b1cd865.png)

I know Phil had the same issue when trying to put Martha Lane Fox's full title so hopefully this is an easy fix. 

Thank you, 
Joe

**Comment by Floppy** [comment]
Interesting. Paging @gilesdring as I know he's looking at this page at the moment :)

**Comment by JoePackman** [comment]
Cheers both :)

**Comment by gilesdring** [comment]
Yes, I'd noticed this. Will see if I can tweak the css to avoid it.
